version: "3.8"
services:
  nv-cubb:
    container_name: nv-cubb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    network_mode: host
    shm_size: 4096m
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /lib/modules:/lib/modules
      - /dev/hugepages:/dev/hugepages
      - /usr/src:/usr/src
      - ./aerial_l1_entrypoint.sh:/opt/nvidia/cuBB/aerial_l1_entrypoint.sh
      - ~/share:/opt/cuBB/share
      - /var/log/aerial:/var/log/aerial
    userns_mode: host
    ipc: "shareable"
    image: cubb-build:23-2
    environment:
      - cuBB_SDK=/opt/nvidia/cuBB
    command: bash -c " rm -rf /tmp/phy.log && chmod +x /opt/nvidia/cuBB/aerial_l1_entrypoint.sh && /opt/nvidia/cuBB/aerial_l1_entrypoint.sh P5G_SCF_FXN_NEU"
    healthcheck:
      test: ["CMD-SHELL",'grep -q "L1 is ready!" /tmp/phy.log && echo 0 || echo 1']
      interval: 20s
      timeout: 5s
      retries: 5
  oai-du-aerial:
    cpuset: "13-20"
    image: oai-gnb-aerial:latest
    depends_on:
      nv-cubb:
        condition: service_healthy
    privileged: true
    ipc: "container:nv-cubb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    #network_mode: host
    shm_size: 4096m
    stdin_open: true
    tty: true
    volumes:
      - ../../../targets/PROJECTS/GENERIC-NR-5GC/CONF/du.Aerial.conf:/opt/oai-gnb/etc/gnb.conf
      #- ../../../targets/PROJECTS/GENERIC-NR-5GC/CONF/vnf.sa.band78.fr1.273PRB.Aerial.conf:/opt/oai-gnb/etc/gnb.conf
    container_name: oai-du-aerial
    healthcheck:
      test: /bin/bash -c "ps aux | grep -v grep | grep -c softmodem"
      interval: 10s
      timeout: 5s
      retries: 5      
    networks:
       oai-ran:
          ipv4_address: 192.168.71.141

networks:
    oai-ran:
        driver: bridge
        name: demo-oai-ran
        ipam:
            config:
                - subnet: 192.168.71.128/26
        driver_opts:
            com.docker.network.bridge.name: "demo-oai-ran"
