version: '3.8'
services:
    oai-gnb:
        image: oai-gnb:develop
        privileged: true
        container_name: rfsim5g-oai-gnb
        environment: 
            RFSIMULATOR: server
            USE_SA_TDD_MONO: 'yes'
            GNB_NAME: gnb-rfsim
            #USE_B2XX: 'yes'  #only needed when using B210
            #USE_VOLUMED_CONF: 'yes' #only needed when mounting the configuration file
            TAC: 1
            MCC: '505'
            MNC: '01'
            MNC_LENGTH: 2
            NSSAI_SST: 1
            AMF_IP_ADDRESS: 192.168.70.132
            GNB_NGA_IF_NAME: demo-oai
            GNB_NGA_IP_ADDRESS: 192.168.70.160
            GNB_NGU_IF_NAME: cn5g-access
            GNB_NGU_IP_ADDRESS: 192.168.72.160
            #SDR_ADDRS: serial=XXXXXXX
            #USE_ADDITIONAL_OPTIONS: --sa -E --rfsim --log_config.global_log_options level,nocolor,time   #rfsim
            #USE_ADDITIONAL_OPTIONS: --sa --continuous-tx --log_config.global_log_options level,nocolor,time,line_num,function #(B210)
        volumes:
            - ../ci-scripts/conf_files/gnb.sa.band78.106prb.rfsim.conf:/opt/oai-gnb/etc/gnb.conf        
#volumes:
          #  - shared_lib:/usr/local/lib/flexric/
          #  - ./conf/flexric.conf:/usr/local/etc/flexric/flexric.conf
          #  -  /dev/bus/usb/:/dev/bus/usb/ (B210)
          #  - ./gnb-n77.conf:/opt/oai-gnb/etc/mounted.conf (B210) config file should be present 
        networks:
            public_net:
                ipv4_address: 192.168.70.160
            public_net_access:
                ipv4_address: 192.168.72.160
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-nr-ue:
        image: oai-nrue:develop
        privileged: true
        container_name: rfsim5g-oai-nr-ue
        environment: 
            RFSIMULATOR: 192.168.70.160
            FULL_IMSI: '505010000000020'
            FULL_KEY: '8BAF473F2F8FD09487CCCBD7097C6862'
            OPC: '8e27b6af0e692e750f32667a3b14605d'
            DNN: default
            NSSAI_SST: 1
            #USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 -C 3619200000 --nokrnmod --log_config.global_log_options level,nocolor,time
        volumes:
            - ../ci-scripts/conf_files/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        networks:
            public_net:
                ipv4_address: 192.168.70.161
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-nr-ue2:
        image: oai-nrue:develop
        privileged: true
        container_name: rfsim5g-oai-nr-ue2
        environment: 
            RFSIMULATOR: 192.168.70.160
            FULL_IMSI: '505010000000021'
            FULL_KEY: '8BAF473F2F8FD09487CCCBD7097C6862'
            OPC: '8e27b6af0e692e750f32667a3b14605d'
            DNN: default
            NSSAI_SST: 1
            #USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 -C 3619200000 --nokrnmod --log_config.global_log_options level,nocolor,time
        volumes:
            - ../ci-scripts/conf_files/nrue.uicc2.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        networks:
            public_net:
                ipv4_address: 192.168.70.162
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-nr-ue3:
        image: oai-nrue:develop
        privileged: true
        container_name: rfsim5g-oai-nr-ue3
        environment: 
            RFSIMULATOR: 192.168.70.160
            FULL_IMSI: '505010000000022'
            FULL_KEY: '8BAF473F2F8FD09487CCCBD7097C6862'
            OPC: '8e27b6af0e692e750f32667a3b14605d'
            DNN: default
            NSSAI_SST: 1
            #USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 -C 3619200000 --nokrnmod --log_config.global_log_options level,nocolor,time
        volumes:
            - ../ci-scripts/conf_files/nrue.uicc3.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        networks:
            public_net:
                ipv4_address: 192.168.70.163
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5  
    oai-nr-ue4:
        image: oai-nrue:develop
        privileged: true
        container_name: rfsim5g-oai-nr-ue4
        environment: 
            RFSIMULATOR: 192.168.70.160
            FULL_IMSI: '505010000000023'
            FULL_KEY: '8BAF473F2F8FD09487CCCBD7097C6862'
            OPC: '8e27b6af0e692e750f32667a3b14605d'
            DNN: default
            NSSAI_SST: 1
            #USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 -C 3619200000 --nokrnmod --log_config.global_log_options level,nocolor,time
        volumes:
            - ../ci-scripts/conf_files/nrue.uicc4.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        networks:
            public_net:
                ipv4_address: 192.168.70.164
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5  
    oai-nr-ue5:
        image: oai-nrue:develop
        privileged: true
        container_name: rfsim5g-oai-nr-ue5
        environment: 
            RFSIMULATOR: 192.168.70.160
            FULL_IMSI: '505010000000024'
            FULL_KEY: '8BAF473F2F8FD09487CCCBD7097C6862'
            OPC: '8e27b6af0e692e750f32667a3b14605d'
            DNN: default
            NSSAI_SST: 1
            #USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 -C 3619200000 --nokrnmod --log_config.global_log_options level,nocolor,time
        volumes:
            - ../ci-scripts/conf_files/nrue.uicc5.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        networks:
            public_net:
                ipv4_address: 192.168.70.165
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5  
    oai-nr-ue6:
        image: oai-nrue:develop
        privileged: true
        container_name: rfsim5g-oai-nr-ue6
        environment: 
            RFSIMULATOR: 192.168.70.160
            FULL_IMSI: '505010000000025'
            FULL_KEY: '8BAF473F2F8FD09487CCCBD7097C6862'
            OPC: '8e27b6af0e692e750f32667a3b14605d'
            DNN: default
            NSSAI_SST: 1
            #USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 -C 3619200000 --nokrnmod --log_config.global_log_options level,nocolor,time
        volumes:
            - ../ci-scripts/conf_files/nrue.uicc6.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        networks:
            public_net:
                ipv4_address: 192.168.70.166
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5  
    oai-nr-ue7:
        image: oai-nrue:develop
        privileged: true
        container_name: rfsim5g-oai-nr-ue7
        environment: 
            RFSIMULATOR: 192.168.70.160
            FULL_IMSI: '505010000000026'
            FULL_KEY: '8BAF473F2F8FD09487CCCBD7097C6862'
            OPC: '8e27b6af0e692e750f32667a3b14605d'
            DNN: default
            NSSAI_SST: 1
            #USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 -C 3619200000 --nokrnmod --log_config.global_log_options level,nocolor,time
        volumes:
            - ../ci-scripts/conf_files/nrue.uicc7.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        networks:
            public_net:
                ipv4_address: 192.168.70.167
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5    
    oai-nr-ue8:
        image: oai-nrue:develop
        privileged: true
        container_name: rfsim5g-oai-nr-ue8
        environment: 
            RFSIMULATOR: 192.168.70.160
            FULL_IMSI: '505010000000027'
            FULL_KEY: '8BAF473F2F8FD09487CCCBD7097C6862'
            OPC: '8e27b6af0e692e750f32667a3b14605d'
            DNN: default
            NSSAI_SST: 1
            #USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 -C 3619200000 --nokrnmod --log_config.global_log_options level,nocolor,time
        volumes:
            - ../ci-scripts/conf_files/nrue.uicc8.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        networks:
            public_net:
                ipv4_address: 192.168.70.168
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5   
    oai-nr-ue9:
        image: oai-nrue:develop
        privileged: true
        container_name: rfsim5g-oai-nr-ue9
        environment: 
            RFSIMULATOR: 192.168.70.160
            FULL_IMSI: '505010000000028'
            FULL_KEY: '8BAF473F2F8FD09487CCCBD7097C6862'
            OPC: '8e27b6af0e692e750f32667a3b14605d'
            DNN: default
            NSSAI_SST: 1
            #USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 -C 3619200000 --nokrnmod --log_config.global_log_options level,nocolor,time
        volumes:
            - ../ci-scripts/conf_files/nrue.uicc9.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        networks:
            public_net:
                ipv4_address: 192.168.70.169
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5 
    oai-nr-ue10:
        image: oai-nrue:develop
        privileged: true
        container_name: rfsim5g-oai-nr-ue10
        environment: 
            RFSIMULATOR: 192.168.70.160
            FULL_IMSI: '505010000000029'
            FULL_KEY: '8BAF473F2F8FD09487CCCBD7097C6862'
            OPC: '8e27b6af0e692e750f32667a3b14605d'
            DNN: default
            NSSAI_SST: 1
            #USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 -C 3619200000 --nokrnmod --log_config.global_log_options level,nocolor,time
        volumes:
            - ../ci-scripts/conf_files/nrue.uicc10.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        networks:
            public_net:
                ipv4_address: 192.168.70.170
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5                          
#volumes:
    #shared_lib:

networks:
    public_net:
        driver: bridge
        name: demo-oai-public-net
        ipam:
            config:
                - subnet: 192.168.70.0/24
        driver_opts:
            com.docker.network.bridge.name: "demo-oai"
    public_net_access:
        name: oai-public-access
        ipam:
            config:
                - subnet: 192.168.72.0/24
        driver_opts:
            com.docker.network.bridge.name: "cn5g-access"
